### PR TITLE
Blog description added to file: Update docusaurus.config.js

### PR DESCRIPTION
**Pull request by jdupre81**
Blog description added to file: Update docusaurus.config.js
Linea 42: "false" -> "True" changed.

Screenshot 2023-12-18 at 11 26 39

### CODE REVIEW

**Comment by leafty** [comment]
This is not working. Can you update the description to say what you are trying to do?

**Comment by jdupre81** [comment]
I want to add a description at the top of the page. 

Screenshot 2023-12-18 at 16 03 00

**Review by jdupre81 — COMMENTED** [review]
I want to add a description at the top of the page.

**Comment by leafty** [comment]
Unfortunately, I am not sure how we can do that.

**Pull request closed without merging**
